ARG NODE_VERSION=20

FROM node:${NODE_VERSION} as base

ENV NODE_ENV=development

WORKDIR /src

# Build
FROM base as build

COPY --link package.json yarn.lock ./
# RUN npm install yarn
RUN npm install -g --force yarn && \
  yarn install && \
  yarn cache clean

# Run
FROM base

COPY --from=build /src/node_modules /src/node_modules

CMD [ "yarn", "dev" ]